export const NOTIFY_USER = "NOTIFY_USER";
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";

export const ADD_DEPTH_LEVEL = "ADD_DEPTH_LEVEL";
export const DECREASE_DEPTH_LEVEL = "DECREASE_DEPTH_LEVEL";

export const ADD_PARAGRAPH_TO_TOTAL = "ADD_PARAGRAPH_TO_TOTAL";
export const DECREASE_PARAGRAPH_FROM_TOTAL = "DECREASE_PARAGRAPH_FROM_TOTAL";
export const ADD_PARAGRAPH_LINK = "ADD_PARAGRAPH_LINK";
export const REMOVE_PARAGRAPH_LINK = "REMOVE_PARAGRAPH_LINK";
export const SET_TO_SUDDEN_DEATH = "SET_TO_SUDDEN_DEATH";
export const SET_TO_VICTORY = "SET_TO_VICTORY";
export const SET_TO_FINALBOSS = "SET_TO_FINALBOSS";
export const SET_PARAGRAPH_TYPE = "SET_PARAGRAPH_TYPE";
export const SET_PARAGRAPH_LINK_STATUS = "SET_PARAGRAPH_LINK_STATUS";

export const SYNC_REGISTERS_IN_REDUX = "SYNC_REGISTERS_IN_REDUX";
export const CLEAR_QUEST_DATA = "CLEAR_QUEST_DATA";
export const SET_TO_GLOBAL_SAVING = "SET_TO_GLOBAL_SAVING";
